---
title: "Project 1 Jonathon M's Graphs"
name: "Jonathon Meyer"
output: html_document
---
```{r}
library(ggplot2)
library(dplyr)
library(GGally)
library(ggcorrplot)
library(paletteer)
```


```{r}
N <- NHANES::NHANESraw
slice_sample(N, n=5)
```
## What relationships exist between hypertension, BMI, and Diabetes Presence?
```{r}
N_hyper <- N %>%
  mutate(Hypertension = case_when(BPSysAve >= 130 & BPDiaAve > 80 ~ "Hypertension", BPSysAve < 130 & BPDiaAve <= 80 ~ "Normal Blood Pressure")) %>%
  select(Hypertension, Diabetes, BMI) %>%
  na.omit()

p_BMI <- ggplot(N_hyper, aes(x = Hypertension, y = BMI, fill = Diabetes)) +
  geom_violin() +
  stat_summary(fun.data = function(y) {return(data.frame(y = median(y), ymin = quantile(y, 0.25), ymax = quantile(y, 0.75)))}, geom = "errorbar", width = 0.1, position=position_dodge(width=0.9)) +
  stat_summary(fun = median, mapping = aes(group = Diabetes), position=position_dodge(width=0.9), geom = "point", size = 3, show.legend = F) +
  labs(title = "Association of Diabetes and BMI on Hypertension", x = "BMI", y = "Presence of Hypertension", fill = "Has Diabetes") + 
  ggthemes::theme_foundation() + 
  scale_fill_paletteer_d("dichromat::BluetoGray_8")
p_BMI
```

```{r}
N_hyper_corr <- N_hyper %>%
  mutate(Diabetes = case_when(Diabetes == "Yes" ~ 1, Diabetes == "No" ~ 0)) %>% 
  mutate(Hypertension = case_when(Hypertension == "Hypertension" ~ 1, Hypertension == "Normal Blood Pressure" ~ 0))
N_hyper_p_mat <- cor(N_hyper_corr)
ggcorrplot(N_hyper_p_mat, method = "square", type = "upper", show.diag = F, outline.color = "black", ggtheme = ggthemes::theme_tufte(), lab = T, lab_size = 7)
```
